# Generated by Django 4.2.14 on 2024-07-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentmodel',
            old_name='coins',
            new_name='brilliant_coin',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='bronze_coin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='gold_coin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='ruby_coin',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='silver_coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
