# Generated by Django 4.2.14 on 2024-08-19 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_coins_studentmodel_brilliant_coin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='iht_coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
